version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB}
      - MONGODB_COLLECTION=${MONGODB_COLLECTION}
    volumes:
      - .:/app
    restart: unless-stopped
  db:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    
volumes:
  mongo_data:
