version: "3.8"

services:
  app:
    image: cosmtrek/air:v1.61.5
    container_name: golang_app
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://db:27017}
      - MONGODB_DB=${MONGODB_DB:-books}
      - MONGODB_COLLECTION=${MONGODB_COLLECTION:-books}    
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
  db:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

